version: '3.8'

services:
  pdf_web:
    build: .
    image: pdf_web
    container_name: pdf_web
    ports:
      - 5004:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://pdf_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://pdf_redis:6379/0
    depends_on:
      - pdf_redis
  
  pdf_worker:
    build: .
    command: celery --app project.server.tasks.celery worker --loglevel=info --logfile=project/logs/celery.log
    image: pdf_worker
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://pdf_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://pdf_redis:6379/0
    depends_on:
      - pdf_web
      - pdf_redis
  
  pdf_dashboard:
    build: .
    command: celery --app project.server.tasks.celery flower --port=5555 --broker=redis://pdf_redis:6379/0
    image: pdf_dashboard
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://pdf_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://pdf_redis:6379/0
    depends_on:
      - pdf_web
      - pdf_redis
      - pdf_worker

  pdf_redis:
    image: redis:6-alpine
